apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: forebrain-home-pvc
  namespace: forebrain
  labels:
    app: forebrain
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
