import { expect, test } from '@playwright/test'
import { mkdirSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

import { shot, signIn } from './support'

/**
 * The schedule builder and the two cron surfaces: the schedule a user saves is
 * generated by the builder and previewed by the engine, never typed by hand;
 * the agent page and a project tab keep their jobs to themselves.
 */

/** Each test names its own job: the suite shares one gateway, so a reused
 * name would match the earlier test's row too. */
async function openNewJob(page: import('@playwright/test').Page, name: string) {
  await page.goto('/cron', { waitUntil: 'networkidle' })
  await page.click('[data-testid="cron-new"]')
  await expect(page.locator('[data-testid="cron-editor"]')).toBeVisible()
  await page.fill('[data-testid="cron-name"]', name)
  await page.fill('[data-testid="cron-prompt"]', 'e2e standing prompt')
}

async function saveAndExpectRow(page: import('@playwright/test').Page, name: string, schedule: string) {
  await page.click('[data-testid="cron-save"]')
  await expect(page.locator(`[data-cron-job="${name}"]`)).toBeVisible({ timeout: 15_000 })
  await expect(page.locator(`[data-cron-job="${name}"] .font-mono`)).toHaveText(schedule)
}

test('weekly multi-select builds a cron the engine previews', async ({ page }) => {
  await signIn(page)
  await openNewJob(page, 'weekly brief')
  await page.selectOption('[data-testid="schedule-mode"]', 'weekly')
  await page.locator('[data-testid="schedule-weekdays"] label').filter({ hasText: /周一|Mon/ }).locator('input').check()
  await page.locator('[data-testid="schedule-weekdays"] label').filter({ hasText: /周三|Wed/ }).locator('input').check()
  await page.locator('[data-testid="schedule-weekdays"] label').filter({ hasText: /周五|Fri/ }).locator('input').check()
  await page.fill('[data-testid="schedule-time"]', '09:00')

  // The preview is the engine's parse of the generated cron.
  const preview = page.locator('[data-testid="schedule-preview"]')
  await expect(preview.locator('code')).toHaveText('0 9 * * 1,3,5', { timeout: 10_000 })
  await expect(preview).toContainText(/接下来执行|Next runs/)
  // Three fire times, all in the future, all increasing.
  const times = await preview.locator('span.font-mono').allInnerTexts()
  const parsed = times.map((raw) => Number(new Date(raw.replace(/·/g, '').trim()).getTime() / 1000)).filter((v) => v > 0)
  expect(parsed.length).toBeGreaterThanOrEqual(2)
  for (let i = 1; i < parsed.length; i++) {
    expect(parsed[i]).toBeGreaterThan(parsed[i - 1])
  }

  await saveAndExpectRow(page, 'weekly brief', '0 9 * * 1,3,5')
})

test('relative one-shot saves as in 30m', async ({ page }) => {
  await signIn(page)
  await openNewJob(page, 'relative brief')
  await page.selectOption('[data-testid="schedule-mode"]', 'once-in')
  await page.fill('[data-testid="schedule-in-count"]', '30')
  await page.selectOption('[data-testid="schedule-in-unit"]', 'm')
  await expect(page.locator('[data-testid="schedule-preview"] code')).toHaveText('in 30m', { timeout: 10_000 })
  await saveAndExpectRow(page, 'relative brief', 'in 30m')
})

test('a schedule below the engine floor refuses to save', async ({ page }) => {
  await signIn(page)
  await openNewJob(page, 'floor brief')
  await page.selectOption('[data-testid="schedule-mode"]', 'every')
  // Half a minute is below the engine's one-minute floor; the builder passes
  // it to the preview instead of silently correcting it, and the engine's own
  // message is what the user reads.
  await page.fill('[data-testid="schedule-every-count"]', '0.5')
  await page.selectOption('[data-testid="schedule-every-unit"]', 'm')
  await expect(page.locator('[data-testid="schedule-error"]')).toBeVisible({ timeout: 10_000 })
  await expect(page.locator('[data-testid="cron-save"]')).toBeDisabled()
})

test('edit switches delivery to record-only', async ({ page }) => {
  await signIn(page)
  await openNewJob(page, 'delivery brief')
  await page.selectOption('[data-testid="schedule-mode"]', 'once-in')
  await page.fill('[data-testid="schedule-in-count"]', '30')
  await page.selectOption('[data-testid="cron-deliver"]', '')
  await saveAndExpectRow(page, 'delivery brief', 'in 30m')

  await page.locator('[data-cron-job="delivery brief"]').getByRole('button', { name: /编辑|Edit/ }).click()
  await expect(page.locator('[data-testid="cron-editor"]')).toBeVisible()
  await page.selectOption('[data-testid="cron-deliver"]', '')
  // The editor opens on the stored schedule as it is; saving a change to
  // another field must not rebuild the schedule from the builder's defaults.
  await expect(page.locator('[data-testid="schedule-mode"]')).toHaveValue('cron')
  await expect(page.locator('[data-testid="schedule-cron"]')).toHaveValue('in 30m')
  await page.click('[data-testid="cron-save"]')
  await expect(page.locator('[data-testid="cron-editor"]')).toHaveCount(0, { timeout: 15_000 })
  await expect(page.locator('[data-cron-job="delivery brief"]')).toContainText(/只记录，不投递|Record only/, { timeout: 10_000 })
  await expect(page.locator('[data-cron-job="delivery brief"] .font-mono')).toHaveText('in 30m')
})

test('run now shows up in the run history', async ({ page }) => {
  await signIn(page)
  await openNewJob(page, 'runnow brief')
  await page.selectOption('[data-testid="schedule-mode"]', 'once-in')
  await page.fill('[data-testid="schedule-in-count"]', '30')
  await saveAndExpectRow(page, 'runnow brief', 'in 30m')

  await page.locator('[data-cron-job="runnow brief"]').getByRole('button', { name: /立即执行|Run now/ }).click()
  // The fake provider answers within seconds; the history panel the run
  // button opens shows the row it produced.
  await expect(
    page.locator('[data-cron-job="runnow brief"]'),
  ).toContainText(/成功|ok|执行中|running|失败|failed/i, { timeout: 30_000 })
})

test('project cron jobs stay in the project tab', async ({ page }) => {
  await signIn(page)
  const parent = process.env.E2E_PROJECT_PARENT ?? ''
  test.skip(!parent, 'E2E_PROJECT_PARENT missing')
  const root = `${parent}/cron-e2e-proj`
  mkdirSync(root, { recursive: true })
  writeFileSync(join(root, 'README.md'), 'cron e2e project')

  await page.goto('/projects', { waitUntil: 'networkidle' })
  await page.click('button:has-text("新建项目"), button:has-text("New project")')
  await page.getByRole('textbox', { name: /项目名|Project name/ }).fill('cron-e2e')
  await page.getByRole('textbox', { name: /绝对路径|absolute path/i }).fill(root)
  await page.click('button:has-text("创建"), button:has-text("Create")')
  await page.waitForURL(/\/projects\/.+\/overview/, { timeout: 15_000 })
  await page.click('.project-tab:has-text("定时"), .project-tab:has-text("Cron")')

  await page.click('[data-testid="cron-new"]')
  await page.fill('[data-testid="cron-name"]', 'project brief')
  await page.fill('[data-testid="cron-prompt"]', 'project standing prompt')
  await page.selectOption('[data-testid="schedule-mode"]', 'every')
  await page.fill('[data-testid="schedule-every-count"]', '2')
  await page.locator('[data-testid="schedule-mode"]').selectOption('every')
  await expect(page.locator('[data-testid="schedule-preview"] code')).toHaveText('every 2h', { timeout: 10_000 })
  await page.click('[data-testid="cron-save"]')
  await expect(page.locator('[data-cron-job="project brief"]')).toBeVisible({ timeout: 15_000 })
  await shot(page, 'cron-project')

  // The agent page lists agent-wide jobs only: the project job is not there.
  await page.goto('/cron', { waitUntil: 'networkidle' })
  await expect(page.locator('[data-cron-job="project brief"]')).toHaveCount(0, { timeout: 10_000 })
})
